name       : maim
version    : 5.5.2
release    : 5
source     :
    - https://github.com/naelstrof/maim/archive/v5.5.2.tar.gz : 254563b89c52dcf1fab713c0221db7f3f1a37ec539ecc5512daf5916ba86ed93
license    : GPL-3.0-or-later
component  : system.utils
summary    : maim (Make Image) is a screenshot tool for the command line
description: |
    maim (Make Image) is a screenshot tool for the command line. Developed as an improvement to scrot.
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(xcomposite)
    - pkgconfig(xrandr)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
    - slop-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
