name       : maim
version    : 5.6.3
release    : 7
source     :
    - https://github.com/naelstrof/maim/archive/v5.6.3.tar.gz : b4f9381ec66ce0bd35d7a4f2d83439b253d573a50881c213cacf63b0c00b0863
homepage   : https://github.com/naelstrof/maim/
license    : GPL-3.0-or-later
component  : system.utils
summary    : maim (Make Image) is a screenshot tool for the command line
description: |
    maim (Make Image) is a screenshot tool for the command line. Developed as an improvement to scrot.
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(xcomposite)
    - pkgconfig(xrandr)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
    - slop-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
