name       : maim
version    : 5.4.68
release    : 4
source     :
    - https://github.com/naelstrof/maim/archive/v5.4.68.tar.gz : 25207497a1808d67f2aa940ecd2fbded571e9b480a63ab522e4df6acd9d1a438
license    : GPL-3.0-or-later
component  : system.utils
summary    : maim (Make Image) is a screenshot tool for the command line
description: |
    maim (Make Image) is a screenshot tool for the command line. Developed as an improvement to scrot.
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(xcomposite)
    - pkgconfig(xrandr)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
    - slop-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
