name       : maim
version    : 5.7.4
release    : 10
source     :
    - https://github.com/naelstrof/maim/archive/refs/tags/v5.7.4.tar.gz : 075090fd4c3b87663a26d0c2de63b5c822fd96aaeef6ac4fe6ded3abd506be9e
homepage   : https://github.com/naelstrof/maim/
license    : GPL-3.0-or-later
component  : system.utils
summary    : maim (Make Image) is a screenshot tool for the command line
description: |
    maim (Make Image) is a screenshot tool for the command line. Developed as an improvement to scrot.
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(xcomposite)
    - pkgconfig(xrandr)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - slop-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
