name       : maim
version    : 5.5.3
release    : 6
source     :
    - https://github.com/naelstrof/maim/archive/v5.5.3.tar.gz : eebbe4b170ce9b4fda860d0625fd56103b261d945df775a840b688bfb755282c
license    : GPL-3.0-or-later
component  : system.utils
summary    : maim (Make Image) is a screenshot tool for the command line
description: |
    maim (Make Image) is a screenshot tool for the command line. Developed as an improvement to scrot.
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(xcomposite)
    - pkgconfig(xrandr)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
    - slop-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
