name       : maim
version    : 5.4.63
release    : 1
source     :
    - https://github.com/naelstrof/maim/archive/v5.4.63.tar.gz : 00753b7146348b4c0f76fb4254b3557d344d94db953b395483f1a657ebf09459
license    : GPL-3.0
component  : system.utils 
summary    : maim (Make Image) is a screenshot tool for the command line.
description: |
    maim (Make Image) is a screenshot tool for the command line. Developed as an improvement to scrot.
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(xcomposite)
    - pkgconfig(xrandr)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
    - slop-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
